import type { Project } from "../backend";

function getDomainLabel(domain: unknown): string {
  const key =
    typeof domain === "object" && domain !== null
      ? Object.keys(domain as object)[0]
      : String(domain);
  const labels: Record<string, string> = {
    cse: "Computer Science Engineering",
    aiml: "Artificial Intelligence & Machine Learning",
    ds: "Data Science",
    iot: "Internet of Things",
    cybersecurity: "Cybersecurity",
  };
  return labels[key] || key.toUpperCase();
}

function loadScript(src: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (document.querySelector(`script[src="${src}"]`)) {
      resolve();
      return;
    }
    const script = document.createElement("script");
    script.src = src;
    script.onload = () => resolve();
    script.onerror = () => reject(new Error(`Failed to load script: ${src}`));
    document.head.appendChild(script);
  });
}

export async function generatePPTX(
  project: Project,
  isPremium: boolean,
): Promise<void> {
  await loadScript(
    "https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js",
  );

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const PptxGenJS = (window as any).PptxGenJS;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  pptx.title = project.title;

  const NAVY = "1A2332";
  const TEAL = "14B8A6";
  const WHITE = "FFFFFF";
  const LIGHT_GRAY = "F0F4F8";
  const MUTED = "A0AEC0";
  const DARK = "2D3748";

  const sections = [
    { title: "Abstract", content: project.generatedContent.abstract },
    { title: "Introduction", content: project.generatedContent.introduction },
    {
      title: "Literature Review",
      content: project.generatedContent.literature_review,
    },
    { title: "Methodology", content: project.generatedContent.methodology },
    { title: "System Design", content: project.generatedContent.system_design },
    { title: "Results", content: project.generatedContent.results },
    { title: "Discussion", content: project.generatedContent.discussion },
    { title: "References", content: project.generatedContent.references },
  ];

  // Title Slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: NAVY };

  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "100%",
    h: 0.08,
    fill: { color: TEAL },
    line: { color: TEAL },
  });

  titleSlide.addText("FINAL YEAR PROJECT REPORT", {
    x: 0.5,
    y: 1.2,
    w: "90%",
    h: 0.5,
    fontSize: 14,
    bold: true,
    color: TEAL,
    align: "center",
    fontFace: "Calibri",
  });

  titleSlide.addText(project.title, {
    x: 0.5,
    y: 1.9,
    w: "90%",
    h: 1.5,
    fontSize: 28,
    bold: true,
    color: WHITE,
    align: "center",
    fontFace: "Calibri",
    wrap: true,
  });

  titleSlide.addText(`Domain: ${getDomainLabel(project.domain)}`, {
    x: 0.5,
    y: 3.6,
    w: "90%",
    h: 0.4,
    fontSize: 14,
    color: MUTED,
    align: "center",
    fontFace: "Calibri",
  });

  titleSlide.addText(
    `Generated by ProjectMate | ${new Date().toLocaleDateString("en-IN")}`,
    {
      x: 0.5,
      y: 4.2,
      w: "90%",
      h: 0.35,
      fontSize: 11,
      color: MUTED,
      align: "center",
      fontFace: "Calibri",
      italic: true,
    },
  );

  if (!isPremium) {
    titleSlide.addText("ProjectMate Free Plan", {
      x: 1,
      y: 2.5,
      w: 8,
      h: 1,
      fontSize: 36,
      bold: true,
      color: "CCCCCC",
      align: "center",
      rotate: 45,
      transparency: 70,
      fontFace: "Calibri",
    });
  }

  // Content Slides
  for (const section of sections) {
    const slide = pptx.addSlide();
    slide.background = { color: LIGHT_GRAY };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 1.0,
      fill: { color: NAVY },
      line: { color: NAVY },
    });

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 0.08,
      h: 1.0,
      fill: { color: TEAL },
      line: { color: TEAL },
    });

    slide.addText(section.title, {
      x: 0.2,
      y: 0.1,
      w: "85%",
      h: 0.8,
      fontSize: 22,
      bold: true,
      color: WHITE,
      fontFace: "Calibri",
      valign: "middle",
    });

    slide.addText(project.title, {
      x: 0.2,
      y: 0.1,
      w: "85%",
      h: 0.8,
      fontSize: 10,
      color: MUTED,
      fontFace: "Calibri",
      align: "right",
      valign: "middle",
    });

    slide.addText(section.content, {
      x: 0.4,
      y: 1.2,
      w: 9.2,
      h: 3.8,
      fontSize: 13,
      color: DARK,
      fontFace: "Calibri",
      wrap: true,
      valign: "top",
    });

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 5.1,
      w: "100%",
      h: 0.25,
      fill: { color: NAVY },
      line: { color: NAVY },
    });

    slide.addText(`ProjectMate | ${getDomainLabel(project.domain)}`, {
      x: 0.2,
      y: 5.1,
      w: 6,
      h: 0.25,
      fontSize: 8,
      color: MUTED,
      fontFace: "Calibri",
      valign: "middle",
    });

    if (!isPremium) {
      slide.addText("ProjectMate Free Plan", {
        x: 1,
        y: 2.0,
        w: 8,
        h: 1,
        fontSize: 36,
        bold: true,
        color: "AAAAAA",
        align: "center",
        rotate: 45,
        transparency: 70,
        fontFace: "Calibri",
      });
    }
  }

  await pptx.writeFile({
    fileName: `${project.title.replace(/\s+/g, "_")}_Presentation.pptx`,
  });
}
