export interface ResumeData {
  fullName: string;
  email: string;
  phone: string;
  degree: string;
  institution: string;
  graduationYear: string;
  projectTitle: string;
  domain: string;
  skills: string;
  careerObjective: string;
}

export async function generateResumePDF(data: ResumeData): Promise<void> {
  // Load jsPDF from CDN
  const jsPDFModule = await new Promise<any>((resolve, reject) => {
    if ((window as any).jspdf) {
      resolve((window as any).jspdf);
      return;
    }
    const script = document.createElement("script");
    script.src =
      "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => resolve((window as any).jspdf);
    script.onerror = reject;
    document.head.appendChild(script);
  });

  const { jsPDF } = jsPDFModule;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  // Helper functions
  const addText = (text: string, x: number, yPos: number, options?: any) => {
    doc.text(text, x, yPos, options);
  };

  const addLine = (yPos: number) => {
    doc.setDrawColor(30, 58, 138);
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
  };

  const addSectionHeader = (title: string, yPos: number): number => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 138);
    addText(title.toUpperCase(), margin, yPos);
    addLine(yPos + 2);
    return yPos + 8;
  };

  // ── Header ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  addText(data.fullName, pageWidth / 2, y, { align: "center" });
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const contactLine = [data.email, data.phone].filter(Boolean).join("  |  ");
  addText(contactLine, pageWidth / 2, y, { align: "center" });
  y += 4;

  doc.setDrawColor(30, 58, 138);
  doc.setLineWidth(1);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // ── Career Objective ──
  if (data.careerObjective) {
    y = addSectionHeader("Career Objective", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const objectiveLines = doc.splitTextToSize(
      data.careerObjective,
      contentWidth,
    );
    doc.text(objectiveLines, margin, y);
    y += objectiveLines.length * 5 + 8;
  }

  // ── Education ──
  y = addSectionHeader("Education", y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  addText(data.degree || "Bachelor of Technology", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  addText(data.graduationYear || "", pageWidth - margin, y, { align: "right" });
  y += 5;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  addText(data.institution || "University Name", margin, y);
  y += 10;

  // ── Project ──
  if (data.projectTitle) {
    y = addSectionHeader("Projects", y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    addText(data.projectTitle, margin, y);
    if (data.domain) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      addText(`Domain: ${data.domain}`, margin, y + 5);
      y += 5;
    }
    y += 10;
  }

  // ── Skills ──
  if (data.skills) {
    y = addSectionHeader("Technical Skills", y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    const skillsList = data.skills
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    const skillsText = skillsList.join("  •  ");
    const skillLines = doc.splitTextToSize(skillsText, contentWidth);
    doc.text(skillLines, margin, y);
    y += skillLines.length * 5 + 8;
  }

  // ── Footer ──
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  addText(
    "Generated by ProjectMate — ATS-Friendly Resume",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" },
  );

  doc.save(`${data.fullName.replace(/\s+/g, "_")}_Resume.pdf`);
}
