/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectDomain = IDL.Variant({
  'ds' : IDL.Null,
  'cse' : IDL.Null,
  'iot' : IDL.Null,
  'aiml' : IDL.Null,
  'cybersecurity' : IDL.Null,
});
export const ProjectSection = IDL.Record({
  'references' : IDL.Text,
  'results' : IDL.Text,
  'literature_review' : IDL.Text,
  'introduction' : IDL.Text,
  'abstract' : IDL.Text,
  'discussion' : IDL.Text,
  'methodology' : IDL.Text,
  'system_design' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'domain' : ProjectDomain,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'generatedContent' : ProjectSection,
});
export const SubscriptionStatus = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'projectsCount' : IDL.Nat,
  'email' : IDL.Text,
  'subscriptionStatus' : SubscriptionStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDashboardUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createProject' : IDL.Func(
      [IDL.Text, ProjectDomain, IDL.Text],
      [Project],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllProjectsByUser' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInterviewQuestions' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getInterviewQuestionsByCategory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProjectTemplates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ProjectDomain, ProjectSection))],
      ['query'],
    ),
  'getProjectsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getUserData' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDefaultQuestions' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Project], []),
  'updateProjectTemplate' : IDL.Func([ProjectDomain, ProjectSection], [], []),
  'upgradeSubscription' : IDL.Func([], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectDomain = IDL.Variant({
    'ds' : IDL.Null,
    'cse' : IDL.Null,
    'iot' : IDL.Null,
    'aiml' : IDL.Null,
    'cybersecurity' : IDL.Null,
  });
  const ProjectSection = IDL.Record({
    'references' : IDL.Text,
    'results' : IDL.Text,
    'literature_review' : IDL.Text,
    'introduction' : IDL.Text,
    'abstract' : IDL.Text,
    'discussion' : IDL.Text,
    'methodology' : IDL.Text,
    'system_design' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'domain' : ProjectDomain,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'generatedContent' : ProjectSection,
  });
  const SubscriptionStatus = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'projectsCount' : IDL.Nat,
    'email' : IDL.Text,
    'subscriptionStatus' : SubscriptionStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDashboardUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createProject' : IDL.Func(
        [IDL.Text, ProjectDomain, IDL.Text],
        [Project],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllProjectsByUser' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInterviewQuestions' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getInterviewQuestionsByCategory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProjectTemplates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ProjectDomain, ProjectSection))],
        ['query'],
      ),
    'getProjectsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getUserData' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDefaultQuestions' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Project], []),
    'updateProjectTemplate' : IDL.Func([ProjectDomain, ProjectSection], [], []),
    'upgradeSubscription' : IDL.Func([], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };