/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Project {
  'id' : bigint,
  'title' : string,
  'domain' : ProjectDomain,
  'userId' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'generatedContent' : ProjectSection,
}
export type ProjectDomain = { 'ds' : null } |
  { 'cse' : null } |
  { 'iot' : null } |
  { 'aiml' : null } |
  { 'cybersecurity' : null };
export interface ProjectSection {
  'references' : string,
  'results' : string,
  'literature_review' : string,
  'introduction' : string,
  'abstract' : string,
  'discussion' : string,
  'methodology' : string,
  'system_design' : string,
}
export type SubscriptionStatus = { 'premium' : null } |
  { 'free' : null };
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'projectsCount' : bigint,
  'email' : string,
  'subscriptionStatus' : SubscriptionStatus,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDashboardUser' : ActorMethod<[string, string], undefined>,
  'createProject' : ActorMethod<[string, ProjectDomain, string], Project>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllProjectsByUser' : ActorMethod<[], Array<Project>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInterviewQuestions' : ActorMethod<[string, [] | [bigint]], Array<string>>,
  'getInterviewQuestionsByCategory' : ActorMethod<
    [string, [] | [bigint]],
    Array<string>
  >,
  'getProjectTemplates' : ActorMethod<
    [],
    Array<[ProjectDomain, ProjectSection]>
  >,
  'getProjectsByUser' : ActorMethod<[Principal], Array<Project>>,
  'getUserData' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeDefaultQuestions' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<[bigint, string, string], Project>,
  'updateProjectTemplate' : ActorMethod<
    [ProjectDomain, ProjectSection],
    undefined
  >,
  'upgradeSubscription' : ActorMethod<[], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];