/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectSection {
    references: string;
    results: string;
    literature_review: string;
    introduction: string;
    abstract: string;
    discussion: string;
    methodology: string;
    system_design: string;
}
export interface Project {
    id: bigint;
    title: string;
    domain: ProjectDomain;
    userId: Principal;
    createdAt: bigint;
    description: string;
    generatedContent: ProjectSection;
}
export interface UserProfile {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    projectsCount: bigint;
    email: string;
    subscriptionStatus: SubscriptionStatus;
}
export enum ProjectDomain {
    ds = "ds",
    cse = "cse",
    iot = "iot",
    aiml = "aiml",
    cybersecurity = "cybersecurity"
}
export enum SubscriptionStatus {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDashboardUser(name: string, email: string): Promise<void>;
    createProject(title: string, domain: ProjectDomain, description: string): Promise<Project>;
    deleteUser(userId: Principal): Promise<void>;
    getAllProjects(): Promise<Array<Project>>;
    getAllProjectsByUser(): Promise<Array<Project>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInterviewQuestions(domain: string, projectId: bigint | null): Promise<Array<string>>;
    getInterviewQuestionsByCategory(category: string, projectId: bigint | null): Promise<Array<string>>;
    getProjectTemplates(): Promise<Array<[ProjectDomain, ProjectSection]>>;
    getProjectsByUser(userId: Principal): Promise<Array<Project>>;
    getUserData(): Promise<UserProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeDefaultQuestions(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProject(projectId: bigint, title: string, description: string): Promise<Project>;
    updateProjectTemplate(domain: ProjectDomain, template: ProjectSection): Promise<void>;
    upgradeSubscription(): Promise<UserProfile>;
}
import type { Project as _Project, ProjectDomain as _ProjectDomain, ProjectSection as _ProjectSection, SubscriptionStatus as _SubscriptionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDashboardUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDashboardUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDashboardUser(arg0, arg1);
            return result;
        }
    }
    async createProject(arg0: string, arg1: ProjectDomain, arg2: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, to_candid_ProjectDomain_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, to_candid_ProjectDomain_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjectsByUser(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjectsByUser();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjectsByUser();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterviewQuestions(arg0: string, arg1: bigint | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewQuestions(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewQuestions(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getInterviewQuestionsByCategory(arg0: string, arg1: bigint | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterviewQuestionsByCategory(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterviewQuestionsByCategory(arg0, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getProjectTemplates(): Promise<Array<[ProjectDomain, ProjectSection]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectTemplates();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectTemplates();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByUser(arg0: Principal): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByUser(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByUser(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserData(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeDefaultQuestions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultQuestions();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: string): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2);
                return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2);
            return from_candid_Project_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectTemplate(arg0: ProjectDomain, arg1: ProjectSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectTemplate(to_candid_ProjectDomain_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectTemplate(to_candid_ProjectDomain_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async upgradeSubscription(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeSubscription();
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeSubscription();
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ProjectDomain_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectDomain): ProjectDomain {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    projectsCount: bigint;
    email: string;
    subscriptionStatus: _SubscriptionStatus;
}): {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    projectsCount: bigint;
    email: string;
    subscriptionStatus: SubscriptionStatus;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n13(_uploadFile, _downloadFile, value.role),
        projectsCount: value.projectsCount,
        email: value.email,
        subscriptionStatus: from_candid_SubscriptionStatus_n15(_uploadFile, _downloadFile, value.subscriptionStatus)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    domain: _ProjectDomain;
    userId: Principal;
    createdAt: bigint;
    description: string;
    generatedContent: _ProjectSection;
}): {
    id: bigint;
    title: string;
    domain: ProjectDomain;
    userId: Principal;
    createdAt: bigint;
    description: string;
    generatedContent: ProjectSection;
} {
    return {
        id: value.id,
        title: value.title,
        domain: from_candid_ProjectDomain_n7(_uploadFile, _downloadFile, value.domain),
        userId: value.userId,
        createdAt: value.createdAt,
        description: value.description,
        generatedContent: value.generatedContent
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ProjectDomain, _ProjectSection]): [ProjectDomain, ProjectSection] {
    return [
        from_candid_ProjectDomain_n7(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionStatus {
    return "premium" in value ? SubscriptionStatus.premium : "free" in value ? SubscriptionStatus.free : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ds: null;
} | {
    cse: null;
} | {
    iot: null;
} | {
    aiml: null;
} | {
    cybersecurity: null;
}): ProjectDomain {
    return "ds" in value ? ProjectDomain.ds : "cse" in value ? ProjectDomain.cse : "iot" in value ? ProjectDomain.iot : "aiml" in value ? ProjectDomain.aiml : "cybersecurity" in value ? ProjectDomain.cybersecurity : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ProjectDomain, _ProjectSection]>): Array<[ProjectDomain, ProjectSection]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ProjectDomain_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectDomain): _ProjectDomain {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    projectsCount: bigint;
    email: string;
    subscriptionStatus: SubscriptionStatus;
}): {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    projectsCount: bigint;
    email: string;
    subscriptionStatus: _SubscriptionStatus;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role),
        projectsCount: value.projectsCount,
        email: value.email,
        subscriptionStatus: to_candid_SubscriptionStatus_n23(_uploadFile, _downloadFile, value.subscriptionStatus)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    premium: null;
} | {
    free: null;
} {
    return value == SubscriptionStatus.premium ? {
        premium: null
    } : value == SubscriptionStatus.free ? {
        free: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectDomain): {
    ds: null;
} | {
    cse: null;
} | {
    iot: null;
} | {
    aiml: null;
} | {
    cybersecurity: null;
} {
    return value == ProjectDomain.ds ? {
        ds: null
    } : value == ProjectDomain.cse ? {
        cse: null
    } : value == ProjectDomain.iot ? {
        iot: null
    } : value == ProjectDomain.aiml ? {
        aiml: null
    } : value == ProjectDomain.cybersecurity ? {
        cybersecurity: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
